### ISSUE TITLE
Sudden error 

### ISSUE THREAD

**Issue by nisar5071** [linkorb/buckaroo#10]
Hi there,

  I was using the API successfully till date but now suddenly getting this error 

Caught exception: The server was unable to process the request due to an internal error. For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.

Any idea why this happened suddenly?

Regards
Nisar

**Comment by martijngastkemper** [comment]
Could you give me an example of your call. Maybe I can reproduce the error.

**Comment by nisar5071** [comment]
The issue was my clients API which suddenly started returning the amount with a comma (30,25) and I was using the same for AmountDebit , now handling the amount properly and everything is fine now.
Thanks for you reply
