### ISSUE TITLE
Tag a new version to Master

### ISSUE THREAD

**Issue by jkwakman** [linkorb/buckaroo#18]
Dear Joost,

Can you tag a new version to the master branche? After deploying the code i noticed the version tag is still 1.7. Composer will not update the libs to the lastest version.Thank you!

Kind regards,

Jack Kwakman

**Comment by joostfaassen** [comment]
Hi @jkwakman, good point, just tagged v1.8.0. Good luck!

**Comment by jkwakman** [comment]
Thnx! Closed issue.
