### ISSUE TITLE
Push requests

### ISSUE THREAD

**Issue by Revee** [linkorb/buckaroo#7]
Are there any methods hidden in there to easily deal with received push messages, or at least to calculate/check the signature of received messages? ( I said push requests in the title but that sounds too much like a git term haha, I mean of course push messages from the Buckaroo server).

**Comment by joostfaassen** [comment]
Hi @Revee, sorry for the late reply.. no i'm sorry, this library only helps to submit requests to Buckaroo, and doesn't help you handle incoming push requests from Buckaroo.. But: Pull requests are very welcome if you decide to add it :-)
