### ISSUE TITLE
running standalone

### ISSUE THREAD

**Issue by derkroesink** [linkorb/buckaroo#8]
Hi!

trying to implement this API on our webserver, but it seems to crash at the namespace bit while i left the directories original.

also looking for the autoload.php file

please advice!

**Comment by joostfaassen** [comment]
Hi @derkroesink,

The stand-alone usage requires you to run `composer install` in the base directory of the project, to fetch all dependencies and generate the vendor/autoload.php file.

For more information, please check: getcomposer.org

good luck!
Joost
